language: ruby
dist: bionic #18.04
sudo: required
jobs:
  include:
    - stage: "build Vagrant and Libvirt with KVM or QEMU - bionic"
      script:
          - sudo make deploy-libvirt
          - sudo make deploy-vagrant
          - sudo make deploy-boxes
after_success:
    - stage: Finalize
      script: sudo vagrant destroy -f
notifications:
  #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
